spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hellospring
    username: RaiseTech08
    password: Java!123
  sql:
    init:
      mode: always